"use client";

import React, { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Download, Clipboard, Check, Terminal, FileCode2, Share2 } from "lucide-react";
import { HackathonPlan } from "@/lib/openai";

interface ExportPanelProps {
  plan: HackathonPlan;
  selectedIdeaIndex: number;
}

export function ExportPanel({ plan, selectedIdeaIndex }: ExportPanelProps) {
  const [copied, setCopied] = useState(false);
  const [copiedIndex, setCopiedIndex] = useState<string | null>(null);

  const selectedIdea = plan.ideas[selectedIdeaIndex] || plan.ideas[0];

  // Helper to compile Markdown document string
  const compileMarkdownString = React.useCallback(() => {
    return `# Hackathon Project Blueprint: ${selectedIdea.name}
Generated by HackForge AI - Your AI Hackathon Co-Pilot

## 💡 PRODUCT CONCEPT
* **Tagline:** ${selectedIdea.tagline}
* **Difficulty:** ${selectedIdea.difficulty}
* **Innovation Score:** ${selectedIdea.innovationScore}% | Feasibility: ${selectedIdea.feasibilityScore}% | Impact: ${selectedIdea.impactScore}%

### Description
${selectedIdea.description}

### Secret Sauce (Winning Strategy)
${selectedIdea.secretSauce}

---

## 🛠️ TECH STACK RECOMMENDATION
* **Frontend:** ${plan.techStack.frontend.name}
  * *Reasoning:* ${plan.techStack.frontend.reasoning}
* **Backend:** ${plan.techStack.backend.name}
  * *Reasoning:* ${plan.techStack.backend.reasoning}
* **Database:** ${plan.techStack.database.name}
  * *Reasoning:* ${plan.techStack.database.reasoning}
* **AI/ML:** ${plan.techStack.ai_ml.name}
  * *Reasoning:* ${plan.techStack.ai_ml.reasoning}
* **Infrastructure:** ${plan.techStack.infra.name}
  * *Reasoning:* ${plan.techStack.infra.reasoning}

---

## 🏗️ SYSTEM ARCHITECTURE
* **Narrative Overview:** ${plan.architecture.description}

### Components Nodes
${plan.architecture.nodes.map((n) => `- [${n.type.toUpperCase()}] ${n.label}`).join("\n")}

### Data Connections Flows
${plan.architecture.edges.map((e) => `- ${e.source} &rarr; ${e.target} (${e.label})`).join("\n")}

---

## 📅 36-HOUR MVP ROADMAP TIMELINE
${plan.roadmap
  .map(
    (p) => `### ${p.phase} - ${p.milestone}
*Status: ${p.status}*
${p.tasks.map((t) => `- [ ] ${t}`).join("\n")}`
  )
  .join("\n\n")}

---

## 📊 FEATURE PRIORITY MATRIX
${plan.matrix
  .map((m) => `- **[${m.quadrant}] ${m.feature}** (Impact: ${m.impact}/100, Effort: ${m.effort}/100)\n  *Detail:* ${m.description}`)
  .join("\n")}

---

## 🎤 5-SLIDE PITCH DECK STRUCTURE
${plan.pitchDeck.slides
  .map(
    (s) => `### Slide ${s.slideNum}: ${s.title.replace("[Idea Name]", selectedIdea.name)}
*Subtitle: ${s.subtitle}*
${s.points.map((p) => `- ${p.replace("[Idea Name]", selectedIdea.name)}`).join("\n")}
*Speaker Notes Cue:* "${s.notes}"`
  )
  .join("\n\n")}

---

## 👥 TEAM TASK ALLOCATION
### Frontend Developer Checklist
${plan.teamSplit.frontend.tasks.map((t) => `- [ ] ${t}`).join("\n")}

### Backend / AI Architect Checklist
${plan.teamSplit.backend.tasks.map((t) => `- [ ] ${t}`).join("\n")}

### Presenter / Product Lead Checklist
${plan.teamSplit.pitcher.tasks.map((t) => `- [ ] ${t}`).join("\n")}
`;
  }, [plan, selectedIdea]);

  const handleCopy = async (text: string, indexId: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopiedIndex(indexId);
      setTimeout(() => setCopiedIndex(null), 2000);
    } catch (e) {
      console.error(e);
    }
  };

  const handleDownload = () => {
    const mdContent = compileMarkdownString();
    const blob = new Blob([mdContent], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.setAttribute("download", `hackforge-blueprint-${selectedIdea.name.toLowerCase().replace(/\s+/g, "-")}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-bold text-slate-100 flex items-center space-x-2">
          <Terminal className="w-5 h-5 text-indigo-400" />
          <span>Export Blueprint Workspace</span>
        </h2>
        <p className="text-xs text-slate-400 mt-1">
          Generate, download, or copy the compiled co-pilot logs to distribute to your teammates instantly.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto">
        
        {/* Download Markdown Panel */}
        <motion.div
          whileHover={{ y: -3 }}
          className="glass-panel p-6 rounded-2xl border border-white/5 bg-[#0a0f1d]/75 flex flex-col justify-between"
        >
          <div className="space-y-4">
            <div className="flex items-center space-x-2.5 text-cyan-400">
              <div className="p-2 bg-cyan-500/5 border border-cyan-500/20 rounded-lg">
                <FileCode2 className="w-4 h-4" />
              </div>
              <span className="text-xs font-mono font-bold tracking-wider uppercase">DOWNLOAD MD WORKSPACE</span>
            </div>
            <p className="text-xs text-slate-400 leading-relaxed">
              Downloads a formatted Markdown file detailing the selected concept, complete database models, visual flow steps, task splits, and slide notes. Perfect for seeding GitHub repositories or Notion wikis.
            </p>
          </div>

          <button
            type="button"
            onClick={handleDownload}
            className="mt-6 w-full flex items-center justify-center space-x-2 bg-gradient-to-r from-indigo-500 to-cyan-500 hover:from-indigo-400 hover:to-cyan-400 text-white font-semibold text-xs py-3 rounded-xl transition duration-300 border border-white/10 shadow-[0_0_15px_rgba(99,102,241,0.25)]"
          >
            <Download className="w-4 h-4" />
            <span>Download Markdown File</span>
          </button>
        </motion.div>

        {/* Share & Copy Raw Logs Panel */}
        <motion.div
          whileHover={{ y: -3 }}
          className="glass-panel p-6 rounded-2xl border border-white/5 bg-[#0a0f1d]/75 flex flex-col justify-between"
        >
          <div className="space-y-4">
            <div className="flex items-center space-x-2.5 text-purple-400">
              <div className="p-2 bg-purple-500/5 border border-purple-500/20 rounded-lg">
                <Share2 className="w-4 h-4" />
              </div>
              <span className="text-xs font-mono font-bold tracking-wider uppercase">COPY RAW TEXT BUNDLE</span>
            </div>
            <p className="text-xs text-slate-400 leading-relaxed">
              Copies the entire compiled report details to your clipboard. Easily paste contents straight into Discord chat boards, Slack messages, or slide editors to instantly align your project group.
            </p>
          </div>

          <button
            type="button"
            onClick={() => handleCopy(compileMarkdownString(), "all")}
            className="mt-6 w-full flex items-center justify-center space-x-2 bg-slate-800 hover:bg-slate-700 text-slate-200 hover:text-white font-semibold text-xs py-3 rounded-xl transition duration-200 border border-white/10"
          >
            {copiedIndex === "all" ? (
              <>
                <Check className="w-4 h-4 text-emerald-400" />
                <span>Copied to Clipboard!</span>
              </>
            ) : (
              <>
                <Clipboard className="w-4 h-4" />
                <span>Copy Full Report Bundle</span>
              </>
            )}
          </button>
        </motion.div>
      </div>
    </div>
  );
}
export default ExportPanel;
